platform :ios, '11.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'Firebase/Firestore'
  pod 'FirestoreDao', :path => '../'

  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
